trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo Maven
      TRES_USERNAME=MAST TRES_DOMAIN=MST1 mvn package
    displayName: 'Maven'
  
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: target/
      archiveFilePatterns: '*-SNAPSHOT.jar'
      artifactName: snapshot
      artifactType: 'pipeline'
